### PR TITLE
Support mouse wheel scroll

### PR DESCRIPTION
**Pull request by JingMatrix**
Allow simulating mouse scroll under command mousemove

### CODE REVIEW

**Comment by e3rd** [comment]
Thanks, I'll use your feature!

However, in what form should be the arguments? It seems the first has to be `0` (otherwise the effect is blocked) and the second should be just positive or negative number.

```
./ydotool mousemove -w   -- 0 -1  # scrolling down
./ydotool mousemove -w   -- 0 1  # scrolling up
./ydotool mousemove -w   -- 0 100  # also scrolling up
./ydotool mousemove -w   -- 10 100  # effect blocked
```

**Comment by JingMatrix** [comment]
It has been a long time, I'll tell you when I can recall it.

**Comment by e3rd** [comment]
Whoa, you're quick. Now I get it – the first number is for horizontal scrolling. This is the conversion table between clicks in the good old xdotool and ydotool.

```
xdotool click 5 # ydotool mousemove -w -- 0 -1
xdotool click 4 # ydotool mousemove -w -- 0 1
xdotool click 7 # ydotool mousemove -w -- 1 0
xdotool click 6 # ydotool mousemove -w -- -1 0
```

I hope this PR will be merged soon!

**Comment by e3rd** [comment]
Amazing, many thanks to the developer!

**Pull request merged**
